### Import libraries for analysis

In [2]:
import pandas as pd

### Importing dataset into jupyter notebook

In [3]:
df = pd.read_excel(r'C:\Users\Nur Hamizah Ridwan\Downloads\Sample Data for bantu Workspace.xlsx')

In [4]:
df

,first_name,last_name,identification,mobile_phone,mobile_home,gender,date_of_birth,citizenship,country_birth,race,job_title,email,driver_license,mailing_address,mailing_address_postal_code,hours_served,shirt_size
0,Erick,Carvil,4476442876,6593331874,6566735345,Male,02/03/1977,Canada,Canada,Chinese,Programmer III,ecarvil0@vistaprint.com,1,01659 Norway Maple Pass,76547,971,M
1,Yehudi,Bastide,8086259519,6593331871,6566372167,Male,18/10/1957,Taiwan,Taiwan,Chinese,Cost Accountant,ybastide1@storify.com,3,9 Delladonna Park,76548,911,S
2,Fred,Darnody,7905462243,6593331875,6569988852,Male,08/12/1962,Mexico,Mexico,Chinese,Social Worker,fdarnody2@yahoo.com,2,42 Superior Place,76549,865,XXL
3,Reyna,McDowall,7328355946,6593331872,6569549343,Female,08/07/1946,Kazakhstan,Kazakhstan,Chinese,Quality Engineer,rmcdowall3@angelfire.com,1,48683 Chive Hill,76550,466,S
4,Yehudi,Wurz,203386235,6598451315,6568771533,Male,25/05/1995,Russia,Russia,Chinese,Senior Quality Engineer,ywurz4@nationalgeographic.com,2,2 2nd Pass,76551,217,XS
5,Terrill,Wybern,7821277242,6591262992,6569823251,Male,30/05/1966,Indonesia,Indonesia,Chinese,Accounting Assistant II,twybern5@cisco.com,3,19 Barby Center,76552,650,M
6,Jerrylee,Hedylstone,5677594988,6594626458,6561483462,Female,02/02/1966,Paraguay,Paraguay,Chinese,Account Coordinator,jhedylstone6@bandcamp.com,1,7026 Red Cloud Avenue,76553,794,L
7,Chris,McDermid,5678249488,6594428138,6568734259,Male,30/06/1987,China,China,Chinese,Clinical Specialist,cmcdermid7@google.fr,2,51 Shoshone Crossing,76554,17,XS
8,Hally,Verick,6240716474,6591169241,6569657617,Female,13/08/2010,Portugal,Portugal,Chinese,Senior Editor,hverick8@netvibes.com,1,37 Chive Center,76555,226,XS
9,Lottie,Ferns,8949284574,6593372777,6564142493,Female,18/01/1975,Philippines,Philippines,Chinese,Human Resources Manager,lferns9@soup.io,3,380 Jenifer Point,76556,952,XS
10,Olly,Sanday,4431238362,6592339975,6566425361,Male,10/05/1953,South Africa,South Africa,Chinese,Nurse Practicioner,osandaya@technorati.com,3,25 Oriole Trail,76557,332,M
11,Hershel,Fatharly,2578011416,6591976334,6565396492,Male,13/03/1968,Ukraine,Ukraine,Chinese,Research Assistant IV,hfatharlyb@jiathis.com,2,551 Holmberg Parkway,76558,754,L
12,Terrijo,Franklen,5382976294,6592974481,6565721448,Female,05/07/1996,Singapore,Singapore,Chinese,Cost Accountant,tfranklenc@devhub.com,3,15258 Sauthoff Court,76559,93,XXL
13,Karlie,Helgass,2529468373,6598116468,6569983912,Female,16/12/1950,China,China,Malay,Occupational Therapist,khelgassd@marketwatch.com,2,3639 Crowley Drive,76560,93,XXL
14,Anny,Garmon,9928556288,6593743116,6563915311,Female,25/01/1969,France,France,Malay,VP Marketing,agarmone@indiegogo.com,1,87 Bowman Point,76561,564,XXL
15,Raymund,Harmston,4854418266,6596166448,6565126794,Male,01/08/1975,Portugal,Portugal,Malay,VP Sales,rharmstonf@state.tx.us,2,4361 Autumn Leaf Way,76562,114,L
16,Archy,Sustin,6045595434,6597144872,6563754327,Male,08/12/1962,Sweden,Sweden,Malay,Quality Control Specialist,asusting@aol.com,1,419 Dwight Street,76563,461,M
17,Wrennie,Currington,7852607653,6597243827,6565319819,Female,02/09/1975,China,China,Malay,Structural Engineer,wcurringtonh@exblog.jp,2,84 Russell Trail,76564,764,L
18,Ave,Brookes,2521023221,6595979264,6567597425,Male,23/03/1952,Ireland,Ireland,Malay,Analyst Programmer,abrookesi@wikispaces.com,3,68211 Surrey Alley,76565,971,3XL
19,Nikos,Kempshall,6464983305,6597547658,6562683556,Male,22/03/1948,Venezuela,Venezuela,Malay,Senior Cost Accountant,nkempshallj@mozilla.com,3,148 Welch Trail,76566,667,3XL
20,Tillie,Feavyour,1997454011,6592799311,6561792819,Female,09/09/2012,Jamaica,Jamaica,Malay,Marketing Assistant,tfeavyourk@deviantart.com,2,17725 Summer Ridge Plaza,76567,710,3XL
21,Blisse,Petroselli,2088938795,6591626427,6568765741,Female,07/03/1992,United States,United States,Malay,Desktop Support Technician,bpetrosellil@wikia.com,3,0739 Ludington Center,76568,185,XL
22,Tony,Bobasch,5811120699,6593773688,6568881198,Male,07/02/1955,China,China,Malay,Quality Engineer,tbobaschm@dagondesign.com,2,052 Florence Court,76569,792,XS
23,Chelsey,Honniebal,5531299395,6591816913,6569122491,Female,27/07/1980,France,France,Malay,Software Consultant,chonniebaln@newyorker.com,3,1518 Pine View Road,76570,696,M
24,Claybourne,Bohlje,3513352187,6598772376,6565446469,Male,07/02/2008,Indonesia,Indonesia,Malay,Recruiter,cbohljeo@unicef.org,2,11 Fremont Trail,76571,58,XS
25,Robinet,Holdey,2136154937,6593242265,6567915559,Female,16/01/1952,China,China,Indian,Clinical Specialist,rholdeyp@netvibes.com,2,29 Cascade Alley,76572,386,XS
26,Alanah,Ashleigh,1114392908,6595532717,6569294964,Female,15/08/1981,Indonesia,Indonesia,Indian,Cost Accountant,aashleighq@angelfire.com,1,2 Del Mar Crossing,76573,849,S
27,Kaitlyn,Edridge,5271609007,6599833212,6564228929,Female,14/07/1959,France,France,Indian,Sales Representative,kedridger@un.org,3,6 Utah Junction,76574,754,XL
28,Rahel,Nobriga,805296877,6597875989,6565518835,Female,26/08/1952,Indonesia,Indonesia,Indian,Product Engineer,rnobrigas@zimbio.com,1,293 Farmco Crossing,76575,404,L
29,Daren,Ast,4028727136,6599456765,6568323791,Male,09/11/2013,Egypt,Egypt,Indian,Software Test Engineer IV,dastt@jugem.jp,1,2 David Trail,76576,861,M
30,Clyde,Brumfitt,3731728614,6597233834,6568278532,Male,25/09/2003,Bulgaria,Bulgaria,Indian,Research Associate,cbrumfittu@wikia.com,2,1 Muir Center,76577,631,M
31,Horace,Thornborrow,7475324275,6598386892,6569817856,Male,21/06/2005,Vietnam,Vietnam,Indian,Payment Adjustment Coordinator,hthornborrowv@php.net,3,143 Prentice Park,76578,331,XS
32,Cece,Thorp,7151717037,6594443234,6569126838,Male,24/11/1981,Poland,Poland,Indian,Senior Editor,cthorpw@weather.com,1,305 Riverside Alley,76579,750,M
33,Barbie,Eronie,7917302777,6594952977,6561657337,Female,27/07/1999,Uganda,Uganda,Indian,Account Representative IV,beroniex@newyorker.com,1,011 Anthes Lane,76580,379,XL
34,Thomas,Hatrick,1269300605,6596711568,6567793415,Male,20/11/1943,Burundi,Burundi,Indian,Operator,thatricky@cnn.com,1,07 Schurz Road,76581,286,M
35,Corene,Groucock,1456548395,6598857546,6569293899,Female,02/08/1950,Portugal,Portugal,Indian,Design Engineer,cgroucockz@google.com.au,2,6 Vera Hill,76582,349,XL
36,Corbie,Purrington,197998816,6591627135,6569819283,Male,22/04/1944,Mexico,Mexico,Indian,Chief Design Engineer,cpurrington10@sakura.ne.jp,1,4840 Rowland Crossing,76583,698,XS
37,Abram,Peeke,8790329895,6599162927,6569237137,Male,24/05/1971,Ukraine,Ukraine,Indian,Accounting Assistant III,apeeke11@tripadvisor.com,1,34388 Emmet Point,76584,879,L
38,Ruggiero,Henmarsh,4631098614,6596673249,6564788759,Male,03/11/1954,Singapore,Singapore,Indian,Sales Associate,rhenmarsh12@chronoengine.com,1,4 Cascade Crossing,76585,366,XL
39,Claudetta,Fernier,7709531839,6598212254,6562535265,Female,01/01/1990,Iraq,Iraq,Indian,Mechanical Systems Engineer,cfernier13@a8.net,3,8 Sauthoff Parkway,76586,901,XS
40,Sidonia,Baraja,1960827342,6597169711,6564287532,Female,18/03/2009,Nigeria,Nigeria,Indian,Media Manager I,sbaraja14@t-online.de,1,635 Sunnyside Lane,76587,499,M
41,Marjy,Lympenie,3053217820,6594749245,6562625585,Female,14/08/1944,China,China,Caucasian,Financial Advisor,mlympenie15@nasa.gov,3,3073 Ridge Oak Street,76588,972,M
42,Armstrong,Barkshire,522777642,6593635997,6569214661,Male,10/04/1995,China,China,Caucasian,Programmer III,abarkshire16@networksolutions.com,1,884 Cherokee Court,76589,611,L
43,Rurik,Dantesia,27779673,6591542998,6568878911,Male,12/11/1967,Bolivia,Bolivia,Caucasian,Junior Executive,rdantesia17@craigslist.org,1,85 Northfield Circle,76590,728,M
44,Cornelius,Cremer,668087278,6594656847,6561586229,Male,03/04/1993,Uganda,Uganda,Caucasian,VP Accounting,ccremer18@hubpages.com,2,2 Di Loreto Terrace,76591,111,M
45,Laurette,Gwinn,7067475979,6592796985,6569837349,Female,14/09/1990,China,China,Caucasian,Senior Financial Analyst,lgwinn19@google.fr,2,90 Elka Avenue,76592,533,S
46,Daisy,Winslet,1228881022,6592596485,6565622217,Female,16/02/2000,Poland,Poland,Caucasian,Operator,dwinslet1a@deviantart.com,3,6 Bluestem Plaza,76593,955,XL
47,Heddi,Moryson,6932458043,6594919612,6564219176,Female,15/04/1943,Singapore,Singapore,Caucasian,Internal Auditor,hmoryson1b@cocolog-nifty.com,2,75904 Crescent Oaks Junction,76594,501,M
48,Jakob,Hitschke,6889166799,6592338139,6567943157,Male,15/11/2016,Vietnam,Vietnam,Caucasian,Accountant II,jhitschke1c@google.cn,3,7136 Clyde Gallagher Park,76595,805,L
49,Nathalie,Lorden,37400113,6594892416,6568817613,Female,03/12/1949,Philippines,Philippines,Caucasian,Budget/Accounting Analyst IV,nlorden1d@webs.com,2,760 Vahlen Lane,76596,298,M

### To check what dataset we are dealing with

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 17 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   first_name                   50 non-null     object
 1   last_name                    50 non-null     object
 2   identification               50 non-null     int64
 3   mobile_phone                 50 non-null     int64
 4   mobile_home                  50 non-null     int64
 5   gender                       50 non-null     object
 6   date_of_birth                50 non-null     object
 7   citizenship                  50 non-null     object
 8   country_birth                50 non-null     object
 9   race                         50 non-null     object
 10  job_title                    50 non-null     object
 11  email                        50 non-null     object
 12  driver_license               50 non-null     int64
 13  mailing_address              50 non-null     object
 14  mailing_address_postal_code  50 non-null     int64
 15  hours_served                 50 non-null     int64
 16  shirt_size                   50 non-null     object
dtypes: int64(6), object(11)
memory usage: 6.8+ KB

### To check for any null values in the dataset

In [6]:
df.isnull().sum()

first_name                     0
last_name                      0
identification                 0
mobile_phone                   0
mobile_home                    0
gender                         0
date_of_birth                  0
citizenship                    0
country_birth                  0
race                           0
job_title                      0
email                          0
driver_license                 0
mailing_address                0
mailing_address_postal_code    0
hours_served                   0
shirt_size                     0
dtype: int64

### Q1: How many users are Male vs Females?

In [17]:
# Create container to update values
male = 0
female = 0

# Iterate through index of df
for idx in df.index:
    
    # Extract and name variables based on index & columns
    gender = df['gender'][idx]
    
    #Test the logic if gender = male
    if gender == "Male": #True
        male += 1               # Update the values
            
    else: # False
        female += 1            # Update the values

print("Male:", male, "vs", "Female:", female)

Male: 26 vs Female: 24

### Q2: Which country has the most users?

In [8]:
# Create dict to update values
results = {}

# Iterate through index of df
for idx in df.index:
    
    # Extract and name variables based on the index & columns
    citizenship = df['citizenship'][idx]
    #print(citizenship)
    
    # To check if the values are in the results container if not it will be updated
    if citizenship not in results:
        results[citizenship] = 1
    else:
        results[citizenship] += 1

print(results)

{'Canada': 1, 'Taiwan': 1, 'Mexico': 2, 'Kazakhstan': 1, 'Russia': 1, 'Indonesia': 4, 'Paraguay': 1, 'China': 8, 'Portugal': 3, 'Philippines': 2, 'South Africa': 1, 'Ukraine': 2, 'Singapore': 3, 'France': 3, 'Sweden': 1, 'Ireland': 1, 'Venezuela': 1, 'Jamaica': 1, 'United States': 1, 'Egypt': 1, 'Bulgaria': 1, 'Vietnam': 2, 'Poland': 2, 'Uganda': 2, 'Burundi': 1, 'Iraq': 1, 'Nigeria': 1, 'Bolivia': 1}

In [18]:
most_users_country = ''
most_users = 0

for country, count in results.items():
    if count > most_users:
        
        most_users_country = country
        most_users = count
        
print("The country with the most users is", most_users_country, "with", most_users, "users.")

The country with the most users is China with 8 users.

### Q3: How many users have invalid identification value? The correct identification value must have 10 characters.

In [10]:
#Create container to update values
ID = 0

# iterate through index of df
for idx in df.index:
    
    # Extract and name variables based on idx & columns
    identification = str(df['identification'][idx])

    if len(identification) < 10:
        #print(identification, len(identification))
        ID += 1
        
print("The number of users that have invalid identification value:", ID)

The number of users that have invalid identification value: 7

### Q4: How many users have valid and invalid mobile phone numbers? Use the country of birth to check. If user country of birth is Singapore and mobile number is +65 then valid else invalid.

In [11]:
#Create container to update values
valid = 0
invalid = 0

# iterate through index of df
for idx in df.index:
    
    # Extract and name variables based on idx & columns
    mobile_phone = str(df['mobile_phone'][idx])
    mobile_home = str(df['mobile_home'][idx])
    country_birth = df['country_birth'][idx]
    
    #Test the logic if country_birth = Singapore and starts with "65"
    if country_birth == "Singapore": #True
        if mobile_phone.startswith("65") & mobile_home.startswith("65"):
            valid += 1               # Update the values
            
    #Test the logic if country_birth != Singapore and starts with "65"
    else: # False
        if mobile_phone.startswith("65") & mobile_home.startswith("65"):
            invalid += 1            # Update the values
            
print("The number of users born in Singapore:", valid)
print("The number of users not born in Singapore:", invalid)

The number of users born in Singapore: 3
The number of users not born in Singapore: 47

### Q5: Replace driver license 1, 2, 3 to the following: 1 - class A, 2 - class B, 3 - class C [Do not use search, find and replace]

In [12]:
# Iterate through index of df
for idx in df.index:
    
    # Extraction of the driver license value and assign as a variable
    driver_license = df['driver_license'][idx]
    
    # Check for condition
    if driver_license == 1: #True
        
        # Replace the original df value based on df[col][idx]
        df['driver_license'][idx] = "class A"
        
    elif driver_license == 2:
        df['driver_license'][idx] = "class B"
        
    else:
        df['driver_license'][idx] = "class C"
        
print(df)

    first_name    last_name  identification  mobile_phone  mobile_home  \
0        Erick       Carvil      4476442876    6593331874   6566735345
1       Yehudi      Bastide      8086259519    6593331871   6566372167
2         Fred      Darnody      7905462243    6593331875   6569988852
3        Reyna     McDowall      7328355946    6593331872   6569549343
4       Yehudi         Wurz       203386235    6598451315   6568771533
5      Terrill       Wybern      7821277242    6591262992   6569823251
6     Jerrylee   Hedylstone      5677594988    6594626458   6561483462
7        Chris     McDermid      5678249488    6594428138   6568734259
8        Hally       Verick      6240716474    6591169241   6569657617
9       Lottie        Ferns      8949284574    6593372777   6564142493
10        Olly       Sanday      4431238362    6592339975   6566425361
11     Hershel     Fatharly      2578011416    6591976334   6565396492
12     Terrijo     Franklen      5382976294    6592974481   6565721448
13      Karlie      Helgass      2529468373    6598116468   6569983912
14        Anny       Garmon      9928556288    6593743116   6563915311
15     Raymund     Harmston      4854418266    6596166448   6565126794
16       Archy       Sustin      6045595434    6597144872   6563754327
17     Wrennie   Currington      7852607653    6597243827   6565319819
18         Ave      Brookes      2521023221    6595979264   6567597425
19       Nikos    Kempshall      6464983305    6597547658   6562683556
20      Tillie     Feavyour      1997454011    6592799311   6561792819
21      Blisse   Petroselli      2088938795    6591626427   6568765741
22        Tony      Bobasch      5811120699    6593773688   6568881198
23     Chelsey    Honniebal      5531299395    6591816913   6569122491
24  Claybourne       Bohlje      3513352187    6598772376   6565446469
25     Robinet       Holdey      2136154937    6593242265   6567915559
26      Alanah     Ashleigh      1114392908    6595532717   6569294964
27     Kaitlyn      Edridge      5271609007    6599833212   6564228929
28       Rahel      Nobriga       805296877    6597875989   6565518835
29       Daren          Ast      4028727136    6599456765   6568323791
30       Clyde     Brumfitt      3731728614    6597233834   6568278532
31      Horace  Thornborrow      7475324275    6598386892   6569817856
32        Cece        Thorp      7151717037    6594443234   6569126838
33      Barbie       Eronie      7917302777    6594952977   6561657337
34      Thomas      Hatrick      1269300605    6596711568   6567793415
35      Corene     Groucock      1456548395    6598857546   6569293899
36      Corbie   Purrington       197998816    6591627135   6569819283
37       Abram        Peeke      8790329895    6599162927   6569237137
38    Ruggiero     Henmarsh      4631098614    6596673249   6564788759
39   Claudetta      Fernier      7709531839    6598212254   6562535265
40     Sidonia       Baraja      1960827342    6597169711   6564287532
41       Marjy     Lympenie      3053217820    6594749245   6562625585
42   Armstrong    Barkshire       522777642    6593635997   6569214661
43       Rurik     Dantesia        27779673    6591542998   6568878911
44   Cornelius       Cremer       668087278    6594656847   6561586229
45    Laurette        Gwinn      7067475979    6592796985   6569837349
46       Daisy      Winslet      1228881022    6592596485   6565622217
47       Heddi      Moryson      6932458043    6594919612   6564219176
48       Jakob     Hitschke      6889166799    6592338139   6567943157
49    Nathalie       Lorden        37400113    6594892416   6568817613

    gender date_of_birth    citizenship  country_birth       race  \
0     Male    02/03/1977         Canada         Canada    Chinese
1     Male    18/10/1957         Taiwan         Taiwan    Chinese
2     Male    08/12/1962         Mexico         Mexico    Chinese
3   Female    08/07/1946     Kazakhstan     Kazakhstan    Chinese
4     Male    25/05/1995         Russia         Russia    Chinese
5     Male    30/05/1966      Indonesia      Indonesia    Chinese
6   Female    02/02/1966       Paraguay       Paraguay    Chinese
7     Male    30/06/1987          China          China    Chinese
8   Female    13/08/2010       Portugal       Portugal    Chinese
9   Female    18/01/1975    Philippines    Philippines    Chinese
10    Male    10/05/1953   South Africa   South Africa    Chinese
11    Male    13/03/1968        Ukraine        Ukraine    Chinese
12  Female    05/07/1996      Singapore      Singapore    Chinese
13  Female    16/12/1950          China          China      Malay
14  Female    25/01/1969         France         France      Malay
15    Male    01/08/1975       Portugal       Portugal      Malay
16    Male    08/12/1962         Sweden         Sweden      Malay
17  Female    02/09/1975          China          China      Malay
18    Male    23/03/1952        Ireland        Ireland      Malay
19    Male    22/03/1948      Venezuela      Venezuela      Malay
20  Female    09/09/2012        Jamaica        Jamaica      Malay
21  Female    07/03/1992  United States  United States      Malay
22    Male    07/02/1955          China          China      Malay
23  Female    27/07/1980         France         France      Malay
24    Male    07/02/2008      Indonesia      Indonesia      Malay
25  Female    16/01/1952          China          China     Indian
26  Female    15/08/1981      Indonesia      Indonesia     Indian
27  Female    14/07/1959         France         France     Indian
28  Female    26/08/1952      Indonesia      Indonesia     Indian
29    Male    09/11/2013          Egypt          Egypt     Indian
30    Male    25/09/2003       Bulgaria       Bulgaria     Indian
31    Male    21/06/2005        Vietnam        Vietnam     Indian
32    Male    24/11/1981         Poland         Poland     Indian
33  Female    27/07/1999         Uganda         Uganda     Indian
34    Male    20/11/1943        Burundi        Burundi     Indian
35  Female    02/08/1950       Portugal       Portugal     Indian
36    Male    22/04/1944         Mexico         Mexico     Indian
37    Male    24/05/1971        Ukraine        Ukraine     Indian
38    Male    03/11/1954      Singapore      Singapore     Indian
39  Female    01/01/1990           Iraq           Iraq     Indian
40  Female    18/03/2009        Nigeria        Nigeria     Indian
41  Female    14/08/1944          China          China  Caucasian
42    Male    10/04/1995          China          China  Caucasian
43    Male    12/11/1967        Bolivia        Bolivia  Caucasian
44    Male    03/04/1993         Uganda         Uganda  Caucasian
45  Female    14/09/1990          China          China  Caucasian
46  Female    16/02/2000         Poland         Poland  Caucasian
47  Female    15/04/1943      Singapore      Singapore  Caucasian
48    Male    15/11/2016        Vietnam        Vietnam  Caucasian
49  Female    03/12/1949    Philippines    Philippines  Caucasian

                         job_title                              email  \
0                   Programmer III            ecarvil0@vistaprint.com
1                  Cost Accountant              ybastide1@storify.com
2                    Social Worker                fdarnody2@yahoo.com
3                 Quality Engineer           rmcdowall3@angelfire.com
4          Senior Quality Engineer      ywurz4@nationalgeographic.com
5          Accounting Assistant II                 twybern5@cisco.com
6              Account Coordinator          jhedylstone6@bandcamp.com
7              Clinical Specialist               cmcdermid7@google.fr
8                    Senior Editor              hverick8@netvibes.com
9          Human Resources Manager                    lferns9@soup.io
10              Nurse Practicioner            osandaya@technorati.com
11           Research Assistant IV             hfatharlyb@jiathis.com
12                 Cost Accountant              tfranklenc@devhub.com
13          Occupational Therapist          khelgassd@marketwatch.com
14                    VP Marketing             agarmone@indiegogo.com
15                        VP Sales             rharmstonf@state.tx.us
16      Quality Control Specialist                   asusting@aol.com
17             Structural Engineer             wcurringtonh@exblog.jp
18              Analyst Programmer           abrookesi@wikispaces.com
19          Senior Cost Accountant            nkempshallj@mozilla.com
20             Marketing Assistant          tfeavyourk@deviantart.com
21      Desktop Support Technician             bpetrosellil@wikia.com
22                Quality Engineer          tbobaschm@dagondesign.com
23             Software Consultant          chonniebaln@newyorker.com
24                       Recruiter                cbohljeo@unicef.org
25             Clinical Specialist              rholdeyp@netvibes.com
26                 Cost Accountant           aashleighq@angelfire.com
27            Sales Representative                   kedridger@un.org
28                Product Engineer               rnobrigas@zimbio.com
29       Software Test Engineer IV                     dastt@jugem.jp
30              Research Associate               cbrumfittu@wikia.com
31  Payment Adjustment Coordinator              hthornborrowv@php.net
32                   Senior Editor                cthorpw@weather.com
33       Account Representative IV             beroniex@newyorker.com
34                        Operator                  thatricky@cnn.com
35                 Design Engineer           cgroucockz@google.com.au
36           Chief Design Engineer         cpurrington10@sakura.ne.jp
37        Accounting Assistant III           apeeke11@tripadvisor.com
38                 Sales Associate       rhenmarsh12@chronoengine.com
39     Mechanical Systems Engineer                  cfernier13@a8.net
40                 Media Manager I              sbaraja14@t-online.de
41               Financial Advisor               mlympenie15@nasa.gov
42                  Programmer III  abarkshire16@networksolutions.com
43                Junior Executive         rdantesia17@craigslist.org
44                   VP Accounting             ccremer18@hubpages.com
45        Senior Financial Analyst                 lgwinn19@google.fr
46                        Operator          dwinslet1a@deviantart.com
47                Internal Auditor       hmoryson1b@cocolog-nifty.com
48                   Accountant II              jhitschke1c@google.cn
49    Budget/Accounting Analyst IV                 nlorden1d@webs.com

   driver_license               mailing_address  mailing_address_postal_code  \
0         class A       01659 Norway Maple Pass                        76547
1         class C             9 Delladonna Park                        76548
2         class B             42 Superior Place                        76549
3         class A              48683 Chive Hill                        76550
4         class B                    2 2nd Pass                        76551
5         class C               19 Barby Center                        76552
6         class A         7026 Red Cloud Avenue                        76553
7         class B          51 Shoshone Crossing                        76554
8         class A               37 Chive Center                        76555
9         class C             380 Jenifer Point                        76556
10        class C               25 Oriole Trail                        76557
11        class B          551 Holmberg Parkway                        76558
12        class C          15258 Sauthoff Court                        76559
13        class B            3639 Crowley Drive                        76560
14        class A               87 Bowman Point                        76561
15        class B          4361 Autumn Leaf Way                        76562
16        class A             419 Dwight Street                        76563
17        class B              84 Russell Trail                        76564
18        class C            68211 Surrey Alley                        76565
19        class C               148 Welch Trail                        76566
20        class B      17725 Summer Ridge Plaza                        76567
21        class C         0739 Ludington Center                        76568
22        class B            052 Florence Court                        76569
23        class C           1518 Pine View Road                        76570
24        class B              11 Fremont Trail                        76571
25        class B              29 Cascade Alley                        76572
26        class A            2 Del Mar Crossing                        76573
27        class C               6 Utah Junction                        76574
28        class A           293 Farmco Crossing                        76575
29        class A                 2 David Trail                        76576
30        class B                 1 Muir Center                        76577
31        class C             143 Prentice Park                        76578
32        class A           305 Riverside Alley                        76579
33        class A               011 Anthes Lane                        76580
34        class A                07 Schurz Road                        76581
35        class B                   6 Vera Hill                        76582
36        class A         4840 Rowland Crossing                        76583
37        class A             34388 Emmet Point                        76584
38        class A            4 Cascade Crossing                        76585
39        class C            8 Sauthoff Parkway                        76586
40        class A            635 Sunnyside Lane                        76587
41        class C         3073 Ridge Oak Street                        76588
42        class A            884 Cherokee Court                        76589
43        class A          85 Northfield Circle                        76590
44        class B           2 Di Loreto Terrace                        76591
45        class B                90 Elka Avenue                        76592
46        class C              6 Bluestem Plaza                        76593
47        class B  75904 Crescent Oaks Junction                        76594
48        class C     7136 Clyde Gallagher Park                        76595
49        class B               760 Vahlen Lane                        76596

    hours_served shirt_size
0            971          M
1            911          S
2            865        XXL
3            466          S
4            217         XS
5            650          M
6            794          L
7             17         XS
8            226         XS
9            952         XS
10           332          M
11           754          L
12            93        XXL
13            93        XXL
14           564        XXL
15           114          L
16           461          M
17           764          L
18           971        3XL
19           667        3XL
20           710        3XL
21           185         XL
22           792         XS
23           696          M
24            58         XS
25           386         XS
26           849          S
27           754         XL
28           404          L
29           861          M
30           631          M
31           331         XS
32           750          M
33           379         XL
34           286          M
35           349         XL
36           698         XS
37           879          L
38           366         XL
39           901         XS
40           499          M
41           972          M
42           611          L
43           728          M
44           111          M
45           533          S
46           955         XL
47           501          M
48           805          L
49           298          M

<ipython-input-12-85784bc8e59d>:11: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['driver_license'][idx] = "class A"
C:\Users\Nur Hamizah Ridwan\anaconda3\lib\site-packages\pandas\core\indexing.py:670: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  iloc._setitem_with_indexer(indexer, value)
<ipython-input-12-85784bc8e59d>:17: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['driver_license'][idx] = "class C"
<ipython-input-12-85784bc8e59d>:14: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['driver_license'][idx] = "class B"

In [13]:
df

,first_name,last_name,identification,mobile_phone,mobile_home,gender,date_of_birth,citizenship,country_birth,race,job_title,email,driver_license,mailing_address,mailing_address_postal_code,hours_served,shirt_size
0,Erick,Carvil,4476442876,6593331874,6566735345,Male,02/03/1977,Canada,Canada,Chinese,Programmer III,ecarvil0@vistaprint.com,class A,01659 Norway Maple Pass,76547,971,M
1,Yehudi,Bastide,8086259519,6593331871,6566372167,Male,18/10/1957,Taiwan,Taiwan,Chinese,Cost Accountant,ybastide1@storify.com,class C,9 Delladonna Park,76548,911,S
2,Fred,Darnody,7905462243,6593331875,6569988852,Male,08/12/1962,Mexico,Mexico,Chinese,Social Worker,fdarnody2@yahoo.com,class B,42 Superior Place,76549,865,XXL
3,Reyna,McDowall,7328355946,6593331872,6569549343,Female,08/07/1946,Kazakhstan,Kazakhstan,Chinese,Quality Engineer,rmcdowall3@angelfire.com,class A,48683 Chive Hill,76550,466,S
4,Yehudi,Wurz,203386235,6598451315,6568771533,Male,25/05/1995,Russia,Russia,Chinese,Senior Quality Engineer,ywurz4@nationalgeographic.com,class B,2 2nd Pass,76551,217,XS
5,Terrill,Wybern,7821277242,6591262992,6569823251,Male,30/05/1966,Indonesia,Indonesia,Chinese,Accounting Assistant II,twybern5@cisco.com,class C,19 Barby Center,76552,650,M
6,Jerrylee,Hedylstone,5677594988,6594626458,6561483462,Female,02/02/1966,Paraguay,Paraguay,Chinese,Account Coordinator,jhedylstone6@bandcamp.com,class A,7026 Red Cloud Avenue,76553,794,L
7,Chris,McDermid,5678249488,6594428138,6568734259,Male,30/06/1987,China,China,Chinese,Clinical Specialist,cmcdermid7@google.fr,class B,51 Shoshone Crossing,76554,17,XS
8,Hally,Verick,6240716474,6591169241,6569657617,Female,13/08/2010,Portugal,Portugal,Chinese,Senior Editor,hverick8@netvibes.com,class A,37 Chive Center,76555,226,XS
9,Lottie,Ferns,8949284574,6593372777,6564142493,Female,18/01/1975,Philippines,Philippines,Chinese,Human Resources Manager,lferns9@soup.io,class C,380 Jenifer Point,76556,952,XS
10,Olly,Sanday,4431238362,6592339975,6566425361,Male,10/05/1953,South Africa,South Africa,Chinese,Nurse Practicioner,osandaya@technorati.com,class C,25 Oriole Trail,76557,332,M
11,Hershel,Fatharly,2578011416,6591976334,6565396492,Male,13/03/1968,Ukraine,Ukraine,Chinese,Research Assistant IV,hfatharlyb@jiathis.com,class B,551 Holmberg Parkway,76558,754,L
12,Terrijo,Franklen,5382976294,6592974481,6565721448,Female,05/07/1996,Singapore,Singapore,Chinese,Cost Accountant,tfranklenc@devhub.com,class C,15258 Sauthoff Court,76559,93,XXL
13,Karlie,Helgass,2529468373,6598116468,6569983912,Female,16/12/1950,China,China,Malay,Occupational Therapist,khelgassd@marketwatch.com,class B,3639 Crowley Drive,76560,93,XXL
14,Anny,Garmon,9928556288,6593743116,6563915311,Female,25/01/1969,France,France,Malay,VP Marketing,agarmone@indiegogo.com,class A,87 Bowman Point,76561,564,XXL
15,Raymund,Harmston,4854418266,6596166448,6565126794,Male,01/08/1975,Portugal,Portugal,Malay,VP Sales,rharmstonf@state.tx.us,class B,4361 Autumn Leaf Way,76562,114,L
16,Archy,Sustin,6045595434,6597144872,6563754327,Male,08/12/1962,Sweden,Sweden,Malay,Quality Control Specialist,asusting@aol.com,class A,419 Dwight Street,76563,461,M
17,Wrennie,Currington,7852607653,6597243827,6565319819,Female,02/09/1975,China,China,Malay,Structural Engineer,wcurringtonh@exblog.jp,class B,84 Russell Trail,76564,764,L
18,Ave,Brookes,2521023221,6595979264,6567597425,Male,23/03/1952,Ireland,Ireland,Malay,Analyst Programmer,abrookesi@wikispaces.com,class C,68211 Surrey Alley,76565,971,3XL
19,Nikos,Kempshall,6464983305,6597547658,6562683556,Male,22/03/1948,Venezuela,Venezuela,Malay,Senior Cost Accountant,nkempshallj@mozilla.com,class C,148 Welch Trail,76566,667,3XL
20,Tillie,Feavyour,1997454011,6592799311,6561792819,Female,09/09/2012,Jamaica,Jamaica,Malay,Marketing Assistant,tfeavyourk@deviantart.com,class B,17725 Summer Ridge Plaza,76567,710,3XL
21,Blisse,Petroselli,2088938795,6591626427,6568765741,Female,07/03/1992,United States,United States,Malay,Desktop Support Technician,bpetrosellil@wikia.com,class C,0739 Ludington Center,76568,185,XL
22,Tony,Bobasch,5811120699,6593773688,6568881198,Male,07/02/1955,China,China,Malay,Quality Engineer,tbobaschm@dagondesign.com,class B,052 Florence Court,76569,792,XS
23,Chelsey,Honniebal,5531299395,6591816913,6569122491,Female,27/07/1980,France,France,Malay,Software Consultant,chonniebaln@newyorker.com,class C,1518 Pine View Road,76570,696,M
24,Claybourne,Bohlje,3513352187,6598772376,6565446469,Male,07/02/2008,Indonesia,Indonesia,Malay,Recruiter,cbohljeo@unicef.org,class B,11 Fremont Trail,76571,58,XS
25,Robinet,Holdey,2136154937,6593242265,6567915559,Female,16/01/1952,China,China,Indian,Clinical Specialist,rholdeyp@netvibes.com,class B,29 Cascade Alley,76572,386,XS
26,Alanah,Ashleigh,1114392908,6595532717,6569294964,Female,15/08/1981,Indonesia,Indonesia,Indian,Cost Accountant,aashleighq@angelfire.com,class A,2 Del Mar Crossing,76573,849,S
27,Kaitlyn,Edridge,5271609007,6599833212,6564228929,Female,14/07/1959,France,France,Indian,Sales Representative,kedridger@un.org,class C,6 Utah Junction,76574,754,XL
28,Rahel,Nobriga,805296877,6597875989,6565518835,Female,26/08/1952,Indonesia,Indonesia,Indian,Product Engineer,rnobrigas@zimbio.com,class A,293 Farmco Crossing,76575,404,L
29,Daren,Ast,4028727136,6599456765,6568323791,Male,09/11/2013,Egypt,Egypt,Indian,Software Test Engineer IV,dastt@jugem.jp,class A,2 David Trail,76576,861,M
30,Clyde,Brumfitt,3731728614,6597233834,6568278532,Male,25/09/2003,Bulgaria,Bulgaria,Indian,Research Associate,cbrumfittu@wikia.com,class B,1 Muir Center,76577,631,M
31,Horace,Thornborrow,7475324275,6598386892,6569817856,Male,21/06/2005,Vietnam,Vietnam,Indian,Payment Adjustment Coordinator,hthornborrowv@php.net,class C,143 Prentice Park,76578,331,XS
32,Cece,Thorp,7151717037,6594443234,6569126838,Male,24/11/1981,Poland,Poland,Indian,Senior Editor,cthorpw@weather.com,class A,305 Riverside Alley,76579,750,M
33,Barbie,Eronie,7917302777,6594952977,6561657337,Female,27/07/1999,Uganda,Uganda,Indian,Account Representative IV,beroniex@newyorker.com,class A,011 Anthes Lane,76580,379,XL
34,Thomas,Hatrick,1269300605,6596711568,6567793415,Male,20/11/1943,Burundi,Burundi,Indian,Operator,thatricky@cnn.com,class A,07 Schurz Road,76581,286,M
35,Corene,Groucock,1456548395,6598857546,6569293899,Female,02/08/1950,Portugal,Portugal,Indian,Design Engineer,cgroucockz@google.com.au,class B,6 Vera Hill,76582,349,XL
36,Corbie,Purrington,197998816,6591627135,6569819283,Male,22/04/1944,Mexico,Mexico,Indian,Chief Design Engineer,cpurrington10@sakura.ne.jp,class A,4840 Rowland Crossing,76583,698,XS
37,Abram,Peeke,8790329895,6599162927,6569237137,Male,24/05/1971,Ukraine,Ukraine,Indian,Accounting Assistant III,apeeke11@tripadvisor.com,class A,34388 Emmet Point,76584,879,L
38,Ruggiero,Henmarsh,4631098614,6596673249,6564788759,Male,03/11/1954,Singapore,Singapore,Indian,Sales Associate,rhenmarsh12@chronoengine.com,class A,4 Cascade Crossing,76585,366,XL
39,Claudetta,Fernier,7709531839,6598212254,6562535265,Female,01/01/1990,Iraq,Iraq,Indian,Mechanical Systems Engineer,cfernier13@a8.net,class C,8 Sauthoff Parkway,76586,901,XS
40,Sidonia,Baraja,1960827342,6597169711,6564287532,Female,18/03/2009,Nigeria,Nigeria,Indian,Media Manager I,sbaraja14@t-online.de,class A,635 Sunnyside Lane,76587,499,M
41,Marjy,Lympenie,3053217820,6594749245,6562625585,Female,14/08/1944,China,China,Caucasian,Financial Advisor,mlympenie15@nasa.gov,class C,3073 Ridge Oak Street,76588,972,M
42,Armstrong,Barkshire,522777642,6593635997,6569214661,Male,10/04/1995,China,China,Caucasian,Programmer III,abarkshire16@networksolutions.com,class A,884 Cherokee Court,76589,611,L
43,Rurik,Dantesia,27779673,6591542998,6568878911,Male,12/11/1967,Bolivia,Bolivia,Caucasian,Junior Executive,rdantesia17@craigslist.org,class A,85 Northfield Circle,76590,728,M
44,Cornelius,Cremer,668087278,6594656847,6561586229,Male,03/04/1993,Uganda,Uganda,Caucasian,VP Accounting,ccremer18@hubpages.com,class B,2 Di Loreto Terrace,76591,111,M
45,Laurette,Gwinn,7067475979,6592796985,6569837349,Female,14/09/1990,China,China,Caucasian,Senior Financial Analyst,lgwinn19@google.fr,class B,90 Elka Avenue,76592,533,S
46,Daisy,Winslet,1228881022,6592596485,6565622217,Female,16/02/2000,Poland,Poland,Caucasian,Operator,dwinslet1a@deviantart.com,class C,6 Bluestem Plaza,76593,955,XL
47,Heddi,Moryson,6932458043,6594919612,6564219176,Female,15/04/1943,Singapore,Singapore,Caucasian,Internal Auditor,hmoryson1b@cocolog-nifty.com,class B,75904 Crescent Oaks Junction,76594,501,M
48,Jakob,Hitschke,6889166799,6592338139,6567943157,Male,15/11/2016,Vietnam,Vietnam,Caucasian,Accountant II,jhitschke1c@google.cn,class C,7136 Clyde Gallagher Park,76595,805,L
49,Nathalie,Lorden,37400113,6594892416,6568817613,Female,03/12/1949,Philippines,Philippines,Caucasian,Budget/Accounting Analyst IV,nlorden1d@webs.com,class B,760 Vahlen Lane,76596,298,M

In [14]:
df['driver_license'].unique()

array(['class A', 'class C', 'class B'], dtype=object)

In [16]:
df.to_excel(r'C:\Users\Nur Hamizah Ridwan\Downloads\Cleaned2-Sample Data for bantu Workspace.xlsx', index=False)